# Generated by Django 4.2.2 on 2023-11-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("img", models.CharField(blank=True, max_length=250, null=True)),
                ("date", models.CharField(blank=True, max_length=50, null=True)),
                ("weather", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
