# Generated by Django 4.2.2 on 2023-11-15 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.news_data"
                    ),
                ),
            ],
        ),
    ]
