# Generated by Django 4.2.2 on 2023-11-08 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="News",
            new_name="News_data",
        ),
    ]
