# Generated by Django 4.2.2 on 2023-11-17 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
