# Generated by Django 4.2.2 on 2023-11-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_news_data_category_alter_news_data_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news_data",
            name="img",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
