# Generated by Django 4.2.2 on 2023-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_news_data_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="news_data",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
