# Generated by Django 4.2.2 on 2023-11-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_news_data_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news_data",
            name="is_active",
            field=models.BooleanField(default=1),
        ),
    ]
