# Generated by Django 4.2.2 on 2023-12-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_news_data_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.FileField(upload_to="images/")),
                ("video", models.FileField(upload_to="videos/")),
            ],
        ),
    ]
