# Generated by Django 4.2.7 on 2024-01-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variationmanager_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
