# Generated by Django 4.2.2 on 2023-10-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_test_metn"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mesaj", models.CharField(max_length=100)),
                ("ad", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("comment_id", models.IntegerField()),
            ],
        ),
    ]
