# Generated by Django 4.2.2 on 2023-10-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_delete_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=70)),
                ("name", models.CharField(max_length=50)),
                ("comment_id", models.IntegerField()),
            ],
        ),
    ]
