# Generated by Django 4.2.2 on 2023-10-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
