# Generated by Django 3.2.21 on 2023-10-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='basliq',
            field=models.CharField(max_length=100),
        ),
    ]
