# Generated by Django 3.2.21 on 2023-10-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_test_basliq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='basliq',
            field=models.CharField(max_length=500),
        ),
    ]
