# Generated by Django 4.2.2 on 2023-09-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(blank=True, max_length=50, null=True)),
                ('metn', models.TextField(blank=True, max_length=700, null=True)),
                ('tarix', models.DateField(auto_now=True)),
            ],
        ),
    ]
