# Generated by Django 4.2.2 on 2023-09-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefon',
            name='st_id',
        ),
        migrations.AddField(
            model_name='telefon',
            name='st_id',
            field=models.ManyToManyField(to='main.student'),
        ),
    ]
