# Generated by Django 4.2.2 on 2023-09-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_telefon_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefon',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
