# Generated by Django 4.2.2 on 2023-09-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_telefon_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='telefon',
            name='img',
        ),
    ]
