# Generated by Django 4.2.2 on 2023-11-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_delete_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news_data",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
