# Generated by Django 4.2.2 on 2023-09-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefon',
            name='img',
            field=models.FileField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
