# docker-compose.yml
version: '3.9'
services:
db:
image: postgres:16
environment:
POSTGRES_DB: secondhand
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
ports: ["5432:5432"]
volumes: [pgdata:/var/lib/postgresql/data]
redis:
image: redis:7
ports: ["6379:6379"]
api:
build: .
command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:4000"
env_file: .env
ports: ["4000:4000"]
depends_on: [db, redis]
volumes:
pgdata: {}