# Generated by Django 4.2.2 on 2023-10-13 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_customuser_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_01",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(6),
                    django.core.validators.MaxValueValidator(18),
                    django.core.validators.MaxLengthValidator(20),
                    django.core.validators.MinLengthValidator(6),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="text",
            field=models.CharField(
                max_length=50,
                validators=[django.core.validators.EmailValidator("test")],
            ),
        ),
    ]
