# Generated by Django 4.2.2 on 2023-10-13 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_customuser_password_01_alter_customuser_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="password_01",
        ),
    ]
