# Generated by Django 4.2.2 on 2023-10-13 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_customuser_password_01"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_01",
            field=models.CharField(
                default=0,
                max_length=50,
                validators=[
                    django.core.validators.MinValueValidator(6),
                    django.core.validators.MaxValueValidator(18),
                    django.core.validators.MaxLengthValidator(20),
                    django.core.validators.MinLengthValidator(6),
                ],
            ),
            preserve_default=False,
        ),
    ]
